(function () {
  'use strict';
  var script = document.currentScript;
  if (!script || script.tagName.toUpperCase() !== 'SCRIPT') throw new Error('Newphorus embed: unable to locate the current script element.');
  var scriptURL = new URL(script.src, window.location.href);
  var embedURL = new URL('embed.html', scriptURL);
  scriptURL.searchParams.forEach(function (value, key) { embedURL.searchParams.set(key, value); });
  var iframe = document.createElement('iframe');
  iframe.src = embedURL.href;
  iframe.setAttribute('allowfullscreen', '');
  iframe.setAttribute('loading', 'lazy');
  iframe.title = 'Newphorus Scratch project player';
  iframe.style.border = '0';
  var ui = scriptURL.searchParams.get('ui') !== 'false';
  var width = Number(scriptURL.searchParams.get('w')) || 480;
  var height = Number(scriptURL.searchParams.get('h')) || 360;
  iframe.width = String(width);
  iframe.height = String(height + (ui ? 54 : 0));
  script.parentNode.replaceChild(iframe, script);
}());
